config/routes.rb
Donatable::Engine.routes.draw do
  root to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  resources :organizations
end

app/models/donatable/application_record.rb
module Donatable
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/donatable/organization.rb
module Donatable
  class Organization < ApplicationRecord
    include PgSearch
    extend FriendlyId
    acts_as_taggable
    acts_as_taggable_on :tags

    friendly_id :combine_name_and_language, use: :slugged
    pg_search_scope :public_search,
                    against: [:name, :short_description, :long_description],
                    using: :dmetaphone

    validates :name, presence: true
    validates :website, presence: true
    validates :short_description, presence: true
    validates :long_description, presence: true
    validates :language, presence: true

    validates_uniqueness_of :name, scope: :language
    validates_uniqueness_of :website, scope: :language

    has_attached_file :main_image, styles: { medium: '300x300>', thumb: '100x100>' }
    validates_attachment_content_type :main_image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

    has_attached_file :logo_image, styles: { logo: '80x80' }
    validates_attachment_content_type :logo_image, content_type: ['image/jpg', 'image/jpeg', 'image/png']

    paginates_per 5
    
    private

    def combine_name_and_language
      self.name.to_s + '-' + self.language.to_s
    end
  end
end

app/controllers/donatable/application_controller.rb
module Donatable
  class ApplicationController < ActionController::Base
    ActsAsTaggableOn.force_lowercase = true
    protect_from_forgery with: :exception
    before_action :set_locale
    before_action :set_current_user

    private

    def set_locale
      if params[:locale]
        cookies[:locale] = params[:locale]
        redirect_back(fallback_location: root_path)
      end
      cookies[:locale] = params[:locale] || cookies[:locale] || I18n.default_locale
      cookies[:locale] = cookies[:locale].to_sym
      I18n.default_locale = cookies[:locale]
    end

    def set_current_user
      @current_user
      if defined? current_user
        @current_user = current_user
      end
      @current_user
    end
  end
end

app/controllers/donatable/organizations_controller.rb
require_dependency 'donatable/application_controller'

module Donatable
  class OrganizationsController < ApplicationController
    before_action :set_organization, only: [:show, :edit, :update, :destroy]
    before_action :auth, only: [:new, :create, :edit, :update, :destroy]
    # before_action :auth_edit, only: [:edit, :update, :destroy]
    # GET /organizations
    def index
      if params[:search]
        @organizations = Organization.public_search(params[:search]).where(language: cookies[:locale].to_s).page params[:page]

      elsif params[:tag]
        sql = """SELECT taggable_id FROM taggings
                 WHERE taggable_type='Donatable::Organization'
                 AND tag_id IN (SELECT id FROM tags WHERE name='#{params[:tag]}');
              """
        org_ids = []
        ActiveRecord::Base.connection.select_all(sql).each do |org|
          org_ids << org['taggable_id']
        end
        @organizations = Kaminari.paginate_array(Organization.where(language: cookies[:locale].to_s, id: org_ids)).page(params[:page])


      else
        @organizations = Organization.where(language: cookies[:locale]).page params[:page]
      end
    end

    # GET /organizations/1
    def show
    end

    # GET /organizations/new
    def new
      @organization = Organization.new
    end

    # GET /organizations/1/edit
    def edit
    end

    # POST /organizations
    def create

      @organization = Organization.new(organization_params.merge!({user_id: current_user.id}))

      if @organization.save
        redirect_to @organization, notice: 'Organization was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /organizations/1
    def update
      if @organization.update(organization_params)
        redirect_to @organization, notice: 'Organization was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /organizations/1
    def destroy
      @organization.destroy
      redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.friendly.find(params[:id])
    end

    def auth
      unless defined? current_user
        redirect_back(fallback_location: root_path)
        return
      end

      if current_user.nil?
        redirect_back(fallback_location: root_path)
        return
      end
    end

    # def auth_edit
    #   unless defined? current_user
    #     redirect_back(fallback_location: root_path)
    #     return
    #   end
    #
    #   if current_user.nil?
    #     redirect_back(fallback_location: root_path)
    #     return
    #   end
    #
    #   if current_user.id != @organization.user_id
    #     redirect_back(fallback_location: root_path)
    #   end
    # end

    # Only allow a trusted parameter "white list" through.
    def organization_params
      params.require(:organization).permit(:name, :website, :twitter, :facebook,
                                           :phone, :city, :state_or_district, :country,
                                           :banner_url, :logo_url, :short_description,
                                           :long_description, :tag_list, :email, :youtube_url,
                                           :main_image, :logo_image, :language)
    end
  end
end

app/controllers/donatable/static_pages_controller.rb
require_dependency 'donatable/application_controller'

module Donatable
  class StaticPagesController < ApplicationController
    def home
    end

    def about
    end
  end
end

app/helpers/donatable/application_helper.rb
module Donatable
  module ApplicationHelper
  end
end

app/views/donatable/organizations/_form.html.erb
<!-- Error Message -->
 <%= form_with(model: organization, local: true, class: 'rounded-form') do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <!-- FORM ACCORDION -->

    <!-- Basic Information Start -->
    <div id="accordion" class="panel-group" role="tablist" aria-multiselectable="true">
      <div class="card">
        <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
            <!--  
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            -->
              BASIC INFORMATION*
            <!-- </a> -->
          </h5>
        </div>

        <!--
        <div id="collapseOne" class="show" role="tabpanel" aria-labelledby="headingOne">
        -->
        <div>
          <div class="card-block">
              <br>
              <div class="field">
                <%= form.label :name %><br>
                <%= form.text_field :name, id: :organization_name %>
              </div>

              <div class="field">
                <%= form.label :language %>
                <%= form.select :language, [ 'es', 'en'], :prompt => 'Select One' %>
              </div>          

              <div class="field">
                <%= form.label :website %><br>
                <%= form.text_field :website, id: :organization_website %>
              </div>

              <div class="field">
                <%= form.label :email %><br>
                <%= form.text_field :email, id: :organization_email %>
              </div>          

              <div class="field">
                <%= form.label :short_description %><br>
                <%= form.text_field :short_description, id: :organization_short_description %>
              </div>

              <div class="field">
                <%= form.label :long_description %><br>
                <%= form.text_area :long_description, id: :organization_long_description %>
              </div>

              <div class="field">
                <%= form.label :tag_list %><br>
                <%= form.text_field :tag_list, value: organization.tag_list.join(', ') %>
              </div>         

              <div class="field">
                    <%= form.label :featured_image %><br>
                    <p class="required" style="padding:0;">Featured images should be at least 825 pixels wide, and follow a 4:3 ratio (i.e. 825px by 619px)</p>
                    <%= form.file_field :featured_image, id: :organization_main_image %>
              </div>

              <div class="field">
                    <%= form.label :logo_image %><br>
                    <p class="required" style="padding:0;">Use your brand's logo icon only, as a 1:1 ratio image (i.e., 200px by 200px)</p>
                    <%= form.file_field :logo_image, id: :organization_logo_image %>
              </div> 
              
              <p class="required">(*) Required information</p>
          </div>
        </div>
      </div>
    <!-- Basic Information End ---->

    <!-- Contact Information Start -->    
      <div class="card">
        <div class="card-header" role="tab" id="headingTwo">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              <i class="more-less fa fa-plus"></i>
              ADDITIONAL CONTACT INFORMATION
            </a>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="card-block">
              <br>
              <div class="field">
                <%= form.label :phone %><br>
                <%= form.text_field :phone, id: :organization_phone %>
              </div>

              <div class="field">
                <%= form.label :city %><br>
                <%= form.text_field :city, id: :organization_city %>
              </div>

              <div class="field">
                <%= form.label :state_or_district %><br>
                <%= form.text_field :state_or_district, id: :organization_state_or_district %>
              </div>

              <div class="field">
                <%= form.label :country %><br>
                <%= form.text_field :country, id: :organization_country %>
              </div>
          </div>
        </div>
      </div>
    <!-- Contact Information End ---->    

    <!-- Social Media Start -->        
      <div class="card">
        <div class="card-header" role="tab" id="headingThree">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              <i class="more-less fa fa-plus"></i>
              SOCIAL MEDIA
            </a>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="card-block">
              <br>
              <div class="field">
                <%= form.label :facebook %><br>
                <%= form.text_field :facebook, id: :organization_facebook %>
              </div>          

              <div class="field">
                <%= form.label :twitter %><br>
                <%= form.text_field :twitter, id: :organization_twitter %>
              </div>

              <div class="field">
                <%= form.label :youtube_url %><br>
                <%= form.text_field :youtube_url, id: :organization_youtube_url %>
              </div>          

          </div>
        </div>
      </div>
    </div>
<!-- Social Media End ---->    

  <div class="actions col-lg-4 col-md-4 col-sm-12">
    <%= button_tag(type: 'submit', class: 'btn btn-success btn-lg btn-block') do %>
      <i class="fa fa-plus-circle"></i> Submit
    <% end %>
  </div>

<script type="text/javascript">
// Add open/close icons toggle feature to form accordion
    function toggleIcon(e) {
    $(e.target)
        .prev('.card-header')
        .find(".more-less")
        .toggleClass('fa-plus fa-minus');
    }
    $('.panel-group').on('hidden.bs.collapse', toggleIcon);
    $('.panel-group').on('shown.bs.collapse', toggleIcon);
</script>
<% end %>

app/views/donatable/organizations/edit.html.erb
<% content_for :title do %>
    Edit Organization | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <h1 class="display-3">Edit <%= @organization.name %></h1>
                    <p class="lead">
                        <%= @organization.short_description %>
                    </p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 org_logo_container" align="center">
                        <%= image_tag @organization.logo_image(:logo), alt: 'Organization logo', tabindex: 0 %>
                </div>
            </div>
        </div>
    </div>
<% end %>

<% content_for :main do %>
    <div class="col-12 col-md-9 pull-md-3 bd-content">
        <%= render 'form', organization: @organization %>
    </div>
    <div class="col-12 col-md-3 push-md-9 bd-sidebar">
        <h3>More Info</h3>
        <p>Here you can edit the data on file for <%= @organization.name %>.</p>
        <p>Fill out the form details as best as you can and click "Submit" when you are finished.</p>
        <hr/>
        <h4>Quick Links</h4>
        <%#= render 'layouts/donatable/sidebar' %>
        <%= link_to @organization, class: 'btn btn-primary btn-block' do %>
            <i class="fa fa-eye"></i> View Org
        <% end %>
        <%= link_to organizations_path, class: 'btn btn-secondary btn-block' do %>
            <i class="fa fa-arrow-circle-left"></i> Back to Search
        <% end %>
    </div>


<% end %>

app/views/donatable/organizations/index.html.erb
<% content_for :title do %>
    Search Orgs | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron search_jumbotron">
        <div class="container">
              <form class="form-inline org_search">
                <div class="col-lg-9 col-md-9 col-sm-12">  
                    <input class="form-control" id="search" name="search" type="text" placeholder="Type keywords here and click button below to search" aria-label="Search" />
                  </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <button class="btn btn-secondary btn-lg btn-block" type="submit"><i class="fa fa-search"></i> Search</button>
                </div>    
              </form>
        </div>
    </div>
<% end %>

<% content_for :main do %>
<div class="col-12 col-md-9 pull-md-3 bd-content">
    <p id="notice"><%= notice %></p>

            <div class="container">
                <% @organizations.each do |organization| %>
                <div class="row org_card">
                    <div class="col-2">
                        <%= image_tag organization.logo_image(:logo), alt: 'Organization logo', tabindex: 0 %>
                    </div>
                    <div class="col-9">
                        <%= link_to organization.name, organization_path(organization), class: 'org_name' %><br>
                        <i class="fa fa-globe"></i> <%= organization.website %><br>
                        <i class="fa fa-commenting-o"></i> <%= organization.short_description %><br>
                        <i class="fa fa-tags"></i> 
                        <% organization.tag_list.each do |tag|%>
                            <%= link_to tag, "/organizations/?tag=#{tag}", class: 'btn btn-outline-warning btn-sm' %>
                        <% end %>
                    </div>
                    <div class="col-1">
                        <%= organization.language %>
                    </div>
                </div>
                <% end %>
            </div>
    
        <%= paginate @organizations %>
    
</div>
<div class="col-12 col-md-3 push-md-9 bd-sidebar">
    <h3>More Info</h3>
    <p>Use the search form above to find specific organizations that match your query.</p>
    <p>Organizations matching your query will be listed next to this section, where you can view each organization by clicking on it's name.</p>
    <hr/>
    <h3>Tag Cloud</h3>
</div>
<% end %>

app/views/donatable/organizations/new.html.erb
<% content_for :title do %>
    New Organization | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">New Organization</h1>
          <p class="lead">
            Create a new organization to add to this donations drive.
          </p>
        </div>
    </div>
<% end %>

<% content_for :main do %>
    <div class="col-12 col-md-9 pull-md-3 bd-content">
        <%= render 'form', organization: @organization %>
    </div>
    <div class="col-12 col-md-3 push-md-9 bd-sidebar">
        <h3>More Info</h3>
        <p>Here is where you can add an organization to the engine's database.</p>
        <p>Fill out the form details as best as you can and click "Submit" when you are finished.</p>
        <p>For the LANGUAGE query, your choice of "EN" for English or "ES" for Spanish will determine
        where this organization can be searched on the engine, i.e., Spanish organizations will not show up under Search results if the language chosen for your view is English.</p>
        <hr/>
        <h4>Quick Links</h4>
        <%#= render 'layouts/donatable/sidebar' %>
        <%= link_to organizations_path, class: 'btn btn-secondary btn-block' do %>
            <i class="fa fa-arrow-circle-left"></i> Back to Search
        <% end %>
    </div>
<% end %>

app/views/donatable/organizations/show.html.erb
<% content_for :title do %>
    View Organization | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <h1 class="display-3"><%= @organization.name %></h1>
                    <p class="lead">
                        <%= @organization.short_description %>
                    </p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 org_logo_container" align="center">
                        <%= image_tag @organization.logo_image(:logo), alt: 'Organization logo', tabindex: 0 %>
                </div>
            </div>
        </div>
    </div>
<% end %>

<% content_for :main do %>
    <div class="col-12 col-md-9 pull-md-3 bd-content">
        <p id="notice"><%= notice %></p>
        <div class="org_featured_img_container">
            <%= image_tag @organization.main_image(:medium), alt: 'Organization main image', tabindex: 0  %>
        </div>

        <p class="org_info" style="padding:0;">
          Long description:<br>
          <span><%= @organization.long_description %></span>
        </p>
        
        <div id="accordion" class="panel-group" role="tablist" aria-multiselectable="true">
        <!-- Contact Information Start -->    
          <div class="card">
            <div class="card-header" role="tab" id="headingOne">
              <h5 class="mb-0">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                  <i class="more-less fa fa-plus"></i>
                  CONTACT INFORMATION
                </a>
              </h5>
            </div>
            <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
              <div class="card-block">
                  <br>
                    <p class="org_info">
                      Website:<br>
                      <span><a href="<%= @organization.website %>"><%= @organization.website %></a></span>
                    </p>

                    <p class="org_info">
                      Email:<br>
                      <span><%= @organization.email %></span>
                    </p>

                    <p class="org_info">
                      Phone:<br>
                      <span><%= @organization.phone %></span>
                    </p>

                    <p class="org_info">
                      City:<br>
                      <span><%= @organization.city %></span>
                    </p>

                    <p class="org_info">
                      State or district:<br>
                      <span><%= @organization.state_or_district %></span>
                    </p>

                    <p class="org_info">
                      Country:<br>
                      <span><%= @organization.country %></span>
                    </p>

              </div>
            </div>
          </div>
        <!-- Contact Information End ---->    

        <!-- Social Media Start -->        
          <div class="card">
            <div class="card-header" role="tab" id="headingTwo">
              <h5 class="mb-0">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <i class="more-less fa fa-plus"></i>
                  SOCIAL MEDIA
                </a>
              </h5>
            </div>
            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
              <div class="card-block">
                  <br>
                  
                    <p class="org_info">
                      Facebook:<br>
                      <span><%= @organization.facebook %></span>
                    </p>
                    
                    <p class="org_info">
                      Twitter:<br>
                      <span><%= @organization.twitter %></span>
                    </p>
                  
                    <p class="org_info">
                      Youtube:<br>
                      <span><%= @organization.youtube_url %></span>
                    </p>

              </div>
            </div>
          </div>
        </div>
        <!-- Social Media End ----> 

        
    </div>
    <div class="col-12 col-md-3 push-md-9 bd-sidebar">
        <h3>More Info</h3>
        <p>Here you can view all of the data for <%= @organization.name %>.</p>
        <p>Use the links below to find similar organizations, or to edit this entry.</p>
        <hr/>
        <%#= render 'layouts/donatable/sidebar' %>
        <h4>Organization Tags</h4>
        <%= @organization.tag_list %>
        <hr/>
        <h4>Similar Organizations</h4>
        <% @organization.find_related_tags.each do |organization| %>
          <i class="fa fa-arrow-right"></i> <%= link_to organization.name, organization_path(organization) %> <br/>
        <% end %>
        <hr/>
        <h4>Quick Links</h4>
        <% if Rails.application.routes.url_helpers.method_defined?(:destroy_user_session_path) %>
          <% if current_user %>
            <%= link_to edit_organization_path(@organization), class: 'btn btn-warning btn-block' do %>
                <i class="fa fa-pencil"></i> Edit Org
            <% end %>
          <% end %>
        <% end %>
        <%= link_to organizations_path, class: 'btn btn-secondary btn-block' do %>
            <i class="fa fa-arrow-circle-left"></i> Back to Search
        <% end %>
    </div>

<script type="text/javascript">
// Add open/close icons toggle feature to form accordion
    function toggleIcon(e) {
    $(e.target)
        .prev('.card-header')
        .find(".more-less")
        .toggleClass('fa-plus fa-minus');
    }
    $('.panel-group').on('hidden.bs.collapse', toggleIcon);
    $('.panel-group').on('shown.bs.collapse', toggleIcon);
</script>
<% end %>

app/views/donatable/static_pages/about.html.erb
<% content_for :title do %>
    About Donatable | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">About</h1>
          <p class="lead">
            Who we are and why we made Donatable.
          </p>
        </div>
    </div>
<% end %>

<% content_for :main do %>
    <div class="col-12 col-md-9 pull-md-3 bd-content">
        <div class="content_block">
            <h2>Why we made donatable.</h2>
            <p>Donatable was created in response to a call on GitHub for a reusable donations website after Hurricane Maria.</p>
        </div>
        <div class="content_block">
        <h3>Who we are</h3>
            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
        </div>
    </div>
    <div class="col-12 col-md-3 push-md-9 bd-sidebar">
        <h3>More Info</h3>
        <img src="http://via.placeholder.com/400x300" width="100%" height="auto" alt="placeholder" tabindex="0" />
        <hr/>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <%#= render 'layouts/donatable/sidebar' %>
    </div>
<% end %>

app/views/donatable/static_pages/home.html.erb
<% content_for :title do %>
    Home | Donatable
<% end %>

<% content_for :jumbotron do %>
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"><%= t :welcome %></h1>
          <p class="lead">
            <%= t :main_subheader %>
          </p>
        </div>
    </div>
<% end %>

<% content_for :main do %>
    <div class="col-12 bd-content">
        <div class="content_block">
            <h2>Features</h2>
            <ul>
              <li>Multilingual - Spanish and English are included and more languages can easily be added</li>
              <li>Accessibile - A focus on accessibility so the app is usable by all.</li>
              <li>Powerful Search - Our search engine can search across the full text added by an organization, and even understands typos.</li>
              <li>Reusable - Can be installed on Heroku with one-click.</li>
              <li>Rails friendly - This app is a Rails Engine, and can be installed into any rails app.</li>
              <li>Mobile ready - Donatable works well on mobile and desktop and anything in between.</li>
            </ul>
        </div>
        <div class="content_block">
            <h3>Who is this for?</h3>
            <ul>
              <li>Relief efforts that would like to have a easy-to-use donations platform.</li>
              <li>Relief apps that would like to add a donations feature as a plugin.</li>
              <li>Anyone looking for a central repository of organizations that can receive a donation.</li>
            </ul>
        </div>
</div>
<% end %>

app/views/layouts/donatable/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/donatable/_navigation.html.erb
<!------------------------------------------>
<!-- user nav -->
<!------------------------------------------>

<div class="container">
  <nav class="navbar navbar-expand-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_url %>">Donatable</a>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item active">
            <a class="nav-link" href="<%= root_url %>">
              <i class="fa fa-home"></i> Home
                <!-- <span class="sr-only">(current)</span> -->
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<%= about_path %>">
              <i class="fa fa-info-circle"></i> About
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<%= organizations_path %>">
                <i class="fa fa-search"></i> Search
            </a>
        </li>
        <% if Rails.application.routes.url_helpers.method_defined?(:destroy_user_session_path) %>
          <% if current_user %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" tabindex="0" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user"></i> Admin
                </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/organizations/new">
                            <i class="fa fa-plus-circle"></i> Add Org
                        </a>
                        <a class="dropdown-item" href="/admin">
                            <i class="fa fa-plus-circle"></i> Admin Panel
                        </a>
                        <%= link_to 'Sign out', main_app.destroy_user_session_path, class: "dropdown-item", method: :delete %>
                    </div>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">
                  <i class="fa fa-sign-in"></i> Login</a>
            </li>
          <% end %>
        <% end %>
        </ul>
        <% unless cookies[:locale] == :en %>
            <a class="nav-link">
                <%= link_to "English", params.permit(:locale).merge(locale: :en) %>
            </a>
        <% end %>
        <% unless cookies[:locale] == :es %>
            <a class="nav-link">
                <%= link_to "Español", params.permit(:locale).merge(locale: :es) %>
            </a>
        <% end %>
    </div> <!-- end navbar -->
  </nav> <!-- end nav -->
</div> <!-- end container -->

app/views/layouts/donatable/_sidebar.html.erb
<!------------------------------------------>
<!-- standards sidebar menu items -->
<!------------------------------------------>

<a class="btn btn-outline-success btn-block" role="button">
    <i class="fa fa-lightbulb-o"></i> Request A Feature
</a>
<a class="btn btn-outline-danger btn-block"role="button">
    <i class="fa fa-bug"></i> Report A Bug
</a>